### ISSUE TITLE
[EPIC] Basic Stability Testing - Periodic upload of 20MB files to Swarm

### ISSUE THREAD

**Issue by holisticode** [ethersphere/user-stories#1]
## Rationale ##
Swarm wants to continuously release updated versions. 

## Owner ##
@holisticode 

## Stakeholder Point of Contact ##
@nonsense 

## Description ##

As a dapp developer on swarm, I should be able to upload periodically files to a private swarm deployment and retrieve them successfully. This epic is about establishing a baseline for 20MB files - upload speed, download speed.

## Context ##
Swarm announced a 0.4 stable release

## User-story Issues ##

- [ ]  https://github.com/ethersphere/go-ethereum/issues/1152
- [ ] https://github.com/ethersphere/go-ethereum/issues/1309
- [ ] https://github.com/ethersphere/go-ethereum/issues/934

## Acceptance criteria ##
* Every minute I should be able to upload a 20MB file
* Upload speed [Take the average -20% buffer to establish base-line to improve on that.]
* Download speed [Take the average -20% buffer to establish base-line to improve on that.]
* No-Error over a period of 10 hrs [Take the average -20% buffer to establish base-line to improve on that.]
* Have behavior tests which cover the upper acceptance criteria [Anton]

## Proof ##

**Comment by FantasticoFox** [comment]
any updates @nonsense ?

**Comment by FantasticoFox** [comment]
How can we get this closed? @nonsense whats the proof? Whats the missing gap?

DO we need a UAT - User Acceptance Test with a defined proof that it worked without errors for 24hrs 3 days in a row or so?

**Comment by nonsense** [comment]
This user story was the primary requirement for stability for the v0.4 release.

We didn't document it as rigorously as we plan to define and document all the future milestones for the 100MB, 200MB, 1GB, etc. uploads.

The release notes for the v0.4 can be found at https://www.reddit.com/r/ethswarm/comments/bpqxeu/swarm_v040_released/

For this particular user story, we ran multiple deployments of various sizes (50-100 Swarm nodes) and we successfully uploaded and retrieved 20MB files every minute or two minutes, depending on configuration. I don't have Grafana screenshots right now to upload here unfortunately.

In terms of download speed and upload speed the release performed much better compared to our previous releases.
