### ISSUE TITLE
[EPIC] Datafund 100 GB Epic

### ISSUE THREAD

**Issue by FantasticoFox** [ethersphere/user-stories#2]
## Rationale ##
based on Datafund / Fair Data Society

Google Doc with the EF agreement: https://docs.google.com/document/d/1d6QxK9pzRoynnRg4VVqH1kSOSeLyC2xryrZhfncZHUE/edit

## Owner ##
@justElad @holisticode 

## Stakeholder Point of Contact ##
Dan Nickless & Gregor Žavcer 

## Dependencies ##
EPIC #1 (Completed)

## Timeline ##
Started April 2019
Target Q3 / Q4 2019

## Description ##
Variant A (with partner delivering)
A user is able to upload through  https://fairdrop.xyz/ a large file and is able to share this file via link with another person which is able to download that file via browser from their local computer.

Variant B (without partner delivering, backup)
Dapp Developer is uploading through the CLI a largeFile to a locally run swarm node and download the large file (Same File) from a different client from any other swarm node in the network. The uploader is notified over the success sync. of the file in the swarm network.

## Context ##

From Datafund (press release): 
https://medium.com/altcoin-magazine/datafund-just-launched-decentralised-file-transfer-on-ethcc-interview-with-the-co-founder-bfd8991f8585

“Through Datafund Fair Data Society already has a fruitful history of working together with the awesome Swarm team. Our plans for the future include the deepening of this collaboration through joint campaigns in our Fair Data Society DAC. One we’re particularly excited about building the capability to send 100 GB files over the Swarm network with the Fairdrop dapp. With such incredible capabilities even an ordinary email function becomes a file sharing titan and decentralized solutions become something that opens up a whole new array of possibilities.” 

User-Story Interface https://fairdrop.xyz/

## Architecture Overview ##
![Architecture diagram](https://github.com/ethersphere/user-stories/blob/master/img/Swarm-Architecture-MVP.png?raw=true)

## Acceptance criteria ##
All sub milestones are reached

- [ ] Download accessible through BZZ LINK
- [ ] Maximum acceptable times (needs to be challenged from the users / stakeholders)
- [ ] Upload 10 hrs - we should establish and continue with a baseline
- [ ] Syncing 19 hrs  - we should establish and continue with a baseline
- [ ] Download 15 hrs (will strongly increase after establishing concurrent download, not part of the MVP)
- [ ] File is available for 24 hrs - estimation with current utilization of the network
- [ ] The uploader gets notified by the network through their local api if the synching is complete
- [ ] Download is directly available after synching

Definition of Test-Environment
@skylenet

**Comment by FantasticoFox** [comment]
Related issue https://github.com/ethersphere/swarm/pull/1395 (please reference)

**Comment by acud** [comment]
related to (and somewhat dependent on) https://github.com/ethersphere/user-stories/issues/51
