### ISSUE TITLE
[EPIC] Adaptive Clients for Swarm

### ISSUE THREAD

**Issue by FantasticoFox** [ethersphere/user-stories#8]
## Rationale ##

This EPIC aims to form a broad collaboration for developing and implementing adaptive nodes for swarm (also known as light nodes).

The collaboration is intended to set requirements, specifications and implement a production grade adaptive/light node for Swarm[p0] suitable for resource-restricted devices (bandwidth, cpu and disk) that is minimally capable of supporting PSS[p1], and transferring files across the network [p2].

Please write users-stories how you would like to use light-clients and to specify your specific requirements.

## Timeline ##
Started June 2019
Target Q3 / Q4 2019

## Owner ##

Louis  (Product Owner Communication Layer (LightNode, PSS, Feeds)
Daniel (Swarm, Research).

## Stakeholder Point of Contact ##

- Oskar (Status.im Point of contact)
- Dan (Datafund Point of contact)
- Attilia (Fefele Foundation Point of contact)

There is a two weekly meeting on tuesdays which is hosted by Oskar to sync stakeholder on this project. 

## Dependencies ##
 
- [ ] Requirements engineering for
- [ ]  Storage Layer - Adaptive Client Mobile / Browser
- [ ]  Communication Layer - Adaptive Client Mobile / Browser
- [ ] Devp2p to Libp2p transition

## Issues ##

- [ ]  Issue one
- [ ]  issue two
- [ ]  issue three

**Comment by FantasticoFox** [comment]
@nolash please add all related user-stories after clarification

**Comment by nolash** [comment]
@FantasticoFox you have written `devp2p to Libp2p transition` here. I do not think that can be in scope for Q3. Where did you get this dependency from?

**Comment by nolash** [comment]
Obsoleted by https://github.com/ethersphere/user-stories/issues/35
